# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

services:
  bank_pg:
    image: postgres
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: bank_card
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network:
    driver: bridge