server:
  port: 8080


spring:
  profiles:
    active: dev

  application:
    name: bank-cards

  docker:
    compose:
      enabled: false

  devtools:
    livereload:
      enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/bank_card}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:example}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yaml

app:
  jwt:
    secret: iNa0fyrTACIZxkT2fu9kET4FtF1BJbIviNa0fyrTACIZxkT2fu9kET4FtF1BJbIv
    expiration-time-min: 15
  cors:
    origins:
    - https://localhost:8080
    - http://localhost:8080
  crypto:
    key: 1234567890123456
    vector: abcdef9876543210

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    root: info
    web: debug
    org:
      hibernate:
        sql: debug
        orm.jdbc.bind: trace
      springframework:
        cache: trace
        orm.jpa.JpaTransactionManager: debug
        security: trace